### ISSUE TITLE
object-class, name-binding, packages, allomorphs are present in UML for historical and current performances

### ISSUE THREAD

**Issue by krgaurav29** [openBackhaul/tdmContainer#11]
object-class, name-binding, packages, allomorphs are present in UML for historical and current performances, which should be removed

**Comment by openBackhaul** [comment]
UML and YANG have already been corrected.
Existing implementations are basing on the corrected YANG.

**Proposal to the 5G-xhaul call on 28th of July 2021:**
Just closing the issue
