### ISSUE TITLE
number-of-historical-performance-sets and time-of-latest-change is present in yang file but not in UML for historical-performance

### ISSUE THREAD

**Issue by krgaurav29** [openBackhaul/tdmContainer#12]

**Comment by openBackhaul** [comment]
**Draft**
**Proposal to the 5G-xhaul call on July 28th of July:**
It has been decided to remove TdmContainerCurrentPerformance and TdmContainerHistoricalPerformances classes from the TdmContainer modelling in [issue#13](https://github.com/openBackhaul/tdmContainer/issues/13).
As a consequence of that decision, this issue became obsolete. It shall be closed without any further activity.

**Comment by openBackhaul** [comment]
**Decision made on the 5G-xhaul call on 28th of July 2021:**
Issue just to be closed without further action.
