### ISSUE TITLE
performance-data is empty for historical and current performances in UML

### ISSUE THREAD

**Issue by krgaurav29** [openBackhaul/tdmContainer#13]

**Comment by openBackhaul** [comment]
**Draft**
**Proposal to the 5G-xhaul call on July 28th of July:**
Because there are no performance values defined for the TdmContainer, TdmContainerCurrentPerformance and TdmContainerHistoricalPerformances classes and subordinated datatypes shall be removed from the TdmContainer modelling.

**Comment by PrathibaJee** [comment]
As a part of this issue , we are removing all performance related entities from tdm-container. 
But we have the following attributes available in the model, 

- tdm-container-capability/performance-monitoring-is-avail
- tdm-container-configuration/performance-monitoring-is-on
- tdm-container-status/performance-monitoring-is-up

Kindly let me know whether we require this attributes ? or do we have to further discuss to remove them?
Also tdm-container-status/statistics-is-up attribute is there. Is this attribute related to performance ? If so, do we need to think about this attribute as well?

**Comment by openBackhaul** [comment]
The following attributes are obsolete and will be deleted from the modeling:
* tdm-container-capability/performance-monitoring-is-avail
* tdm-container-configuration/performance-monitoring-is-on
* tdm-container-status/performance-monitoring-is-up
* tdm-container-status/statistics-is-up
