### ISSUE TITLE
tdm-container-kind attribute type needs to update in UML diagram

### ISSUE THREAD

**Issue by krgaurav29** [openBackhaul/tdmContainer#15]
tdm-container-kind is simple string type in yang and current device implementation for this attribute is also as string but in UML diagram it is represented as tdm-container-kind list.

**Comment by openBackhaul** [comment]
DMIP call on 15th of July analysed the UML and the YANG and could not find anything to be corrected in relation to the description of this issue.
**It has been decided to immediately close this issue without further activity.**
