### ISSUE TITLE
leafref changes for path and must statement to point the same LTP instance.

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/tdmContainer#16]
**Problem :** 
For the attribute tdm-container-kind in tdm-container-configuration , pyang tool reports warning with regards to the must statements defined , 

> tdm-container-2-0.yang:474: warning: node "tdm-container-2-0::tdm-container-capability" is config false and is not part of the accessible tree

the current "must" statement for the attribute is not pointing to the capabilities of the same LTP instance.

**Possible solution :**

```
leaf tdm-container-kind {
                type leafref {
                    path "/core-model:control-construct/core-model:logical-termination-point[core-model:uuid = current()/../../../../core-model:uuid]/core-model:layer-protocol[core-model:local-id = current()/../../../core-model:local-id]/tdm-container:tdm-container-pac/tdm-container:tdm-container-capability/tdm-container:supported-tdm-container-kind-list/tdm-container:tdm-container-name";
                    require-instance false;
                }
                must  'deref(.) = current()';
                description    
                    "Type of TDM container.";
            }
```

**Comment by openBackhaul** [comment]
Solved with [TdmContainer_2.0.0-tsp.220324.1125+yang.1](https://github.com/openBackhaul/tdmContainer/blob/tsp/TdmContainer_2.0.0-tsp.220324.1125+yang.1.zip).
